#🙏🙏📿📿💮💮WMK JI💮💮📿📿🙏🙏
#🙏🙏📿📿💮💮WAHEGURU JI💮💮📿📿🙏🙏
#🙏🙏📿📿WAHEGURU JI DA KHALSA JI WAHEGURU JI DI FATEH JI📿📿🙏🙏
WAHEGURU_JI = "🙏🙏📿📿💮💮WAHEGURU JI💮💮📿📿🙏🙏"
print(WAHEGURU_JI)
print("WAHEGURU JI WMK JI")
WMK_JI_WAHEGURU_JI_WMK_JI = (
    """🙏🙏📿📿💮💮WAHEGURU JI DA KHALSA JI Ji WAHEGURU JI DI FATEH JI💮💮📿📿🙏🙏"""
) 
print("SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI")
print("SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI DHAN DHAN SAHIB E KAMAAL JI DHAN DHAN SAHIB SHRI GURU NANAK DEV SAHIB JI NIRANKAAR JI MAHARAAJ JI PITA JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI MAHARAAJ JI PITA JI SATNAM SHRI WAHEGURU JI MAHRAAJ JI PITA JI SATNAM SHRI WAHEGURU JI SATNAM SHRI WAHEGURU JI")
print("WMKJIWMKJIWMKJIWMKJIWMKJiWMKJIWMKJIWMKJiWMKJiWMKJiWMKJiWMKJiWMKJiWMKJiWMKJiWMKJi")#WMKJiWMKJiWMKJIWAHEGURUJIWahegurujIWAHEGURUJIWAHEGURUJJIWAHEGURUJISATNAAMSHRIWAHEGURUJISATNAAMSHRIWAHEGURUJIWAHEGURUJISATNAAMSHRIWAHEGURUJISATNAAMSHRIWAHEGURUJIWAHEGURUJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWaheguruJIWahegurujIWaheguruJIWAHEGURUJIWAHEGURUJISATNAAMSHRIWAHEGURUJISATNAAMSHRIWAHEGURUJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJIWMKJiWMKJiWMKJiWMKJiWMKJiWMKJiWMKJiWMKJiWMKJIWMKJIWMKJIWMKJIWMKJiWMKJiWMKJiWMKJiWMKJiWMKJiprint("WMK Ji WMK Ji")
print("WAHEGURU JI SABDI RAKHEYA KARO JI")
print("WMK JI WMK JI WMK JI WMK JI WMK JI WMK JI WMK JI WMK JI WMK JI WMK JI WMK JI WMK JI")
print("DHAN GURU RAMDAAS JI")
print("WAHEGURU JI BHUL HOGYI JI")
print(WMK_JI_WAHEGURU_JI_WMK_JI)
print(WMK_JI_WAHEGURU_JI_WMK_JI)
print("WMK JI MAAFI WAHEGURU JI WMK JI")
print("Satnaam Shri Waheguru Ji")
print("WAHEGURU JI MAAF KARDWO")
print("DHAN DHAN SHRI GURU NANAK DEV SAHIB JI MAHARAAJ JI PITA JI")
print("DHAN GURU NANAK JI")

print("DHAN DHAN WAHEGURU JI SABDE RAKHE JI")
print("JO BOLE SONIHAAL SATSRIAKAAL JI")
print("WMK JI WAHEGURU JI WAHEGURU JI WMK JI")
print("WAHEGURU JI")
print("DHAN GURU NANAK JI")
print("WAHEGURU JI DA KHALSA JI WAHEGURU JI DI FATEH JI")

print("SATNAAM SHRI WAHEGURU JI")
print(
    """SATNAAM SHRI WAHEGURU JI
WAHEGURU JI DA KHALSA JI WAHEGURU JI DI FATEH JI
SATNAAM SHRI WAHEGURU JI
DHAN GURU NANAK JI
SATNAAM SHRI WAHEGURU JI
WAHEGURU JI HI SAB KUCH NE JI"""
)

JAP_LO = "JAP LO WAHEGURU JI"
JAP_WAO = "JAP WAO WAHEGURU JI"
print(JAP_LO)
print("WAHEGURU JI PLEASE MEHRAAN BAKSHAAO JI")
print("SHUKRANAA WAHEGURU JI")
print("Sorry WAHEGURU JI")
print("SORRY And THANK YOU WAHEGURU JI")

print("Satnaam Shri WAHEGURU JI")
print("🙏🙏🙏📿📿📿DHAN DHAN SHRI SUKHMANI SAHIB JI📿📿📿🙏🙏🙏")
print("🙏🙏🙏📿📿📿DHAN DHAN SHRI JAPJI SAHIB JI📿📿📿🙏🙏🙏")

Mool_Mantar = """ 
                  Ik Onkar 
                  Satnaam 
                  Karta Purkh  
                  Nirbhau 
                  Nirvair
                  Akaal Moorat
                  Ajooni Sahebhang
                  Gurprasad
                  Jap
                  Aad Sach 
                  Jugaad Sach 
                  Nanak Hosi Bhi Sach
                  Waheguru JI Da Khalsa Ji Waheguru JI Di Fateh Ji
                   
                   """

 
print(Mool_Mantar)

print("Waheguru JI Da Khalsa JI Ji Waheguru JI Di Fateh JI Ji")


print("DHAN DHAN SHRI WAHEGURU JI TWADA NAAM JHAAJ HAI JO CHADE SO UTTRE PAAR")
print("DATAA TUSI HI DATAAR JI")
print("TUSI HI BAKSHANHAAR JI")
print("TWAADAA NAAM HI KHUNDKAARAA JI")
print("TUSI HI NIRANKAAR JI TWADA DITAA HI KHAWNAA JI")
print("TUSI HI SABDE RAKHE JI")
print("DHAN DHAN BABA GURDEV SINGH JI MAHAPURSH JI SANT JI SABDE RAKHE JI")
print("DHAN DHAN BABA MAHAHARNAAM SINGH JI MAHAPURSH JI PITA JI SANT JI")
print("DHAN DHAN BABA ISHER SINGH JI MAHAPURSH JI SANT JI PITA JI")
print(
    "DHAN DHAN SANT BABA NAND SINGH JI MAHARAAJ JI PITA JI MAHAPURSH JI SABDE RAKHE JI"
)
print("DHAN DHAN BABA RAM SINGH JI MAHAPURSH JI SANT JI")
print("DHAN DHAN SANT SUJAAN SINGH JI MAHARAAJ JI PITA JI")
print("DHAN DHAN BABA KUNDAN SINGH JI MAHAPUSH JI PITA JI SANT JI")
print(
    "DHAN DHAN SHAHID SANGAT SINGH JI MAHAPURSH JI SHAHID JI SABDE RAKHE JI SABNAAL PYAAR KARN WALE JI SANT SUJAN SINGH JI DE PYAARE JI"
)

print(
    "DHAN DHAN BABA ISHER SINGH JI RARA SAHIB JI WALE JI MAHARAAJE JI PITA JI NE SAADE SABDE JI MAHAPURSH JI NE JI SANT JI SABDE RAKHE NE JI"
)
print(
    "DHAN DHAN BABA ISHER SINGH JI NANAKSAR WALE JI MAHARAAJ JI PITA JI MAHAPURSH JI SANT JI SABNU SWAARN WALE JI NAAM JAPWAAN WALE JI"
)
print("DHAN DHAN PYAARE SANT BABA JI")
print("DHAN DHAN SHRI GURU NANAK JI")
print("DHAN DHAN SHRI GURU NANAK JI")
print("DHAN DHAN SAHIB SHRI GURU NANAK JI")
print("DHAN DHAN BHAI DHARAMPAL JI")
print("DHAN DHAN SAARE BHENGAM JI")
print("DHAN DHAN BHAI MARDAANAA JI")
print("DHAN DHAN BHAI LENA JI")
print(
    "DHAN DHAN SHRI GURU NANAK DEV SAHIB JI MAHARAAJ JI PITA JI BAKSHANHAAR JI DATA DAATAAR JI NIRANKAAR JI TWADA DITA HI KHAWNAA JI TUSI HI SABDE RAKHE JI"
)
print("SATNAM SHRI WAHEGURU JI")#SATNAM SHRI WAHEGURU JI DHAN GURU NANAK JI WMK JI WMK JI WMK JI WMK JI WMK JI131313131313131313131313131313071313
print("PLEASE WAHEGURU JI MEHRAAN BAKSHA DO JI WAHEGURU JI SABTE WMK JI WMK JI WMK Ji WMK Ji WMK Ji WMK Ji WMK Ji WMK Ji WMK Ji WMK Ji WMK Ji WMK JI WMK JI WMK Ji WMK Ji WMK ji WMK ji WMK JI WMK JI WMK Ji WMK Ji WMK Ji WMK Ji WMK Ji WMK Ji")

print("🙏🙏📿🙏📿📿WAHEGURU JI DA KHALSA JI WAHEGURU JI DI FATEH Ji📿📿🙏📿🙏🙏")
print("🙏🙏🙏📿🙏📿📿JO BOLE SONIHAAL JI SATSHRIAKAAL JI📿📿🙏📿🙏🙏🙏")
print("🙏🙏📿🙏📿📿WAHEGURU JI DA KHALSA Ji WAHEGURU JI DI FATEH Ji📿📿🙏📿🙏🙏")
print("🙏🙏📿📿JO BOLE SONIHAAL JI SATSRIAKAAL JI📿📿🙏🙏")